import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, CheckCircle2, ClipboardList, Eye, FilePlus2, Plus, Search, Trash2, XCircle } from 'lucide-react'
import { api } from '../lib/api'
import type { Challan, ChallanStatus, Customer, Product, User } from '../types'
import { Badge, Button, Card, Empty, Modal } from '../components/ui'
import { dateTime, money } from '../lib/utils'

export function Challans({user,onToast}:{user:User;onToast:(t:'success'|'error',m:string)=>void}){
 const [rows,setRows]=useState<Challan[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[status,setStatus]=useState<ChallanStatus|''>(''),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState<Challan|null>(null)
 const load=()=>{setLoading(true);Promise.all([api.challans.list({limit:50,status:status||undefined}),api.customers.list({limit:100}),api.products.list({limit:100})]).then(([c,cu,p])=>{setRows(c.challans);setCustomers(cu.customers);setProducts(p.products)}).catch(e=>onToast('error',e.message)).finally(()=>setLoading(false))};useEffect(load,[status]);const canCreate=user.role==='ADMIN'||user.role==='SALES'
 const filtered=rows.filter(c=>!search||c.challan_number.toLowerCase().includes(search.toLowerCase())||c.customer?.name.toLowerCase().includes(search.toLowerCase())||c.customer?.business_name?.toLowerCase().includes(search.toLowerCase()))
 return <div className="content-page"><div className="content-title"><div><p className="eyebrow">SALES DOCUMENTS</p><h1>Sales challans</h1><p>Draft, confirm and track stock-moving sales documents.</p></div>{canCreate&&<Button onClick={()=>{setSelected(null);setOpen(true)}}><FilePlus2 size={16}/> New challan</Button>}</div><Card className="table-card"><div className="toolbar"><div className="search-box"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search challan or customer..."/></div><div className="status-filter">{(['','DRAFT','CONFIRMED','CANCELLED'] as const).map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s||'All'}</button>)}</div></div>{loading?<TableSkeleton/>:filtered.length===0?<Empty title="No challans here" description="Create a draft to start a new sales flow."/>:<div className="table-wrap"><table><thead><tr><th>Challan</th><th>Customer</th><th>Lines</th><th>Quantity</th><th>Created</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(c=><tr className="clickable" key={c.id} onClick={()=>{setSelected(c);setOpen(true)}}><td><b className="mono">{c.challan_number}</b></td><td><div><b>{c.customer?.business_name||c.customer?.name}</b><span className="table-sub">{c.customer?.business_name?c.customer?.name:''}</span></div></td><td>{c._count?.items||0}</td><td>{c.total_quantity}</td><td>{dateTime(c.created_at)}</td><td><Status status={c.status}/></td><td><Eye size={16}/></td></tr>)}</tbody></table></div>}</Card><Modal open={open} onClose={()=>setOpen(false)} title={selected?'Challan details':'Create sales challan'} wide>{selected?<ChallanDetail challanId={selected.id} user={user} onClose={()=>setOpen(false)} onRefresh={()=>{setOpen(false);load()}} onToast={onToast}/>:<ChallanForm customers={customers} products={products} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}} onToast={onToast}/>}</Modal></div>
}
function ChallanForm({customers,products,onClose,onSaved,onToast}:{customers:Customer[];products:Product[];onClose:()=>void;onSaved:()=>void;onToast:(t:'success'|'error',m:string)=>void}){const [customer,setCustomer]=useState('');const [items,setItems]=useState<{product_id:string;quantity:number}[]>([{product_id:products[0]?.id||'',quantity:1}]);const [saving,setSaving]=useState(false);const total=items.reduce((a,i)=>a+i.quantity,0);const add=()=>setItems([...items,{product_id:products[0]?.id||'',quantity:1}]);const update=(i:number,k:'product_id'|'quantity',v:any)=>setItems(items.map((x,n)=>n===i?{...x,[k]:v}:x));const remove=(i:number)=>setItems(items.filter((_,n)=>n!==i));const submit=async(e:FormEvent)=>{e.preventDefault();if(!customer)return onToast('error','Select a customer');if(items.some(i=>!i.product_id||i.quantity<1))return onToast('error','Every line needs a valid product and quantity');setSaving(true);try{await api.challans.create({customer_id:customer,items});onToast('success','Draft challan created');onSaved()}catch(e:any){onToast('error',e.message)}finally{setSaving(false)}};return <form onSubmit={submit}><label className="field"><span>Customer</span><select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.business_name||c.name} · {c.name}</option>)}</select></label><div className="line-items-head"><div><p className="eyebrow">LINE ITEMS</p><h3>Products leaving the warehouse</h3></div><Button variant="soft" type="button" onClick={add}><Plus size={15}/> Add line</Button></div><div className="line-items">{items.map((item,i)=>{const p=products.find(x=>x.id===item.product_id);return <div className="line-item" key={i}><div className="line-index">{String(i+1).padStart(2,'0')}</div><select value={item.product_id} onChange={e=>update(i,'product_id',e.target.value)}>{products.map(x=><option key={x.id} value={x.id}>{x.name} · {x.sku}</option>)}</select><div className="qty-wrap"><input min="1" type="number" value={item.quantity} onChange={e=>update(i,'quantity',Number(e.target.value))}/><span>{p?.current_stock??0} available</span></div>{items.length>1&&<button type="button" className="icon-btn danger" onClick={()=>remove(i)}><Trash2 size={16}/></button>}</div>})}</div><div className="challan-summary"><span>Total quantity</span><strong>{total} units</strong><small>Stock is not reduced until the draft is confirmed.</small></div><div className="modal-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit" loading={saving}>Create draft</Button></div></form>}
function ChallanDetail({challanId,user,onClose,onRefresh,onToast}:{challanId:string;user:User;onClose:()=>void;onRefresh:()=>void;onToast:(t:'success'|'error',m:string)=>void}){const [c,setC]=useState<Challan|null>(null);const [busy,setBusy]=useState(false);useEffect(()=>{api.challans.get(challanId).then(setC).catch(e=>onToast('error',e.message))},[challanId]);if(!c)return <div className="detail-loading">Loading challan…</div>;const canAct=(user.role==='ADMIN'||user.role==='SALES')&&c.status==='DRAFT';const act=async(type:'confirm'|'cancel')=>{setBusy(true);try{const next=type==='confirm'?await api.challans.confirm(c.id):await api.challans.cancel(c.id);setC(next);onToast('success',type==='confirm'?'Challan confirmed and stock updated':'Draft challan cancelled');if(type==='confirm')onRefresh()}catch(e:any){onToast('error',e.message)}finally{setBusy(false)}};return <div><div className="profile-hero"><div className="profile-avatar challan"><ClipboardList size={25}/></div><div><h3 className="mono">{c.challan_number}</h3><p>{c.customer?.business_name||c.customer?.name} · {dateTime(c.created_at)}</p></div><div className="profile-status"><Status status={c.status}/></div></div><div className="challan-info"><div><span>Customer</span><b>{c.customer?.business_name||c.customer?.name}</b></div><div><span>Created by</span><b>{c.creator?.name||'—'}</b></div><div><span>Total quantity</span><b>{c.total_quantity} units</b></div></div><div className="detail-section"><div className="section-head"><div><p className="eyebrow">DOCUMENT SNAPSHOT</p><h3>Line items</h3></div></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Unit price</th><th>Quantity</th><th>Line value</th></tr></thead><tbody>{c.items?.map(i=><tr key={i.id}><td><b>{i.product_name_snapshot}</b></td><td className="mono">{i.sku_snapshot}</td><td>{money(i.unit_price_snapshot)}</td><td>{i.quantity}</td><td>{money(Number(i.unit_price_snapshot)*i.quantity)}</td></tr>)}</tbody></table></div></div><div className="security-callout"><CheckCircle2 size={17}/><div><b>Historical snapshot preserved</b><span>The document stores product name, SKU and price at creation time. Confirming this draft will perform a transactional stock deduction.</span></div></div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Close</Button>{canAct&&<Button variant="danger" onClick={()=>act('cancel')} loading={busy}><XCircle size={15}/> Cancel draft</Button>}{canAct&&<Button onClick={()=>act('confirm')} loading={busy}><CheckCircle2 size={15}/> Confirm & reduce stock</Button>}</div></div>}
function Status({status}:{status:ChallanStatus}){return <Badge tone={status==='CONFIRMED'?'success':status==='DRAFT'?'warning':'danger'}>{status}</Badge>}
function TableSkeleton(){return <div className="table-skeleton">{[1,2,3,4,5].map(i=><div key={i}/>)}</div>}
