import { FormEvent, useEffect, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, History, PackagePlus, Search, SlidersHorizontal } from 'lucide-react'
import { api } from '../lib/api'
import type { Product, User } from '../types'
import { Badge, Button, Card, Empty, Modal } from '../components/ui'
import { dateTime } from '../lib/utils'

export function Inventory({user,onToast}:{user:User;onToast:(t:'success'|'error',m:string)=>void}){
 const [products,setProducts]=useState<Product[]>([]),[movements,setMovements]=useState<any[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState<'stock'|'history'>('stock'),[search,setSearch]=useState(''),[open,setOpen]=useState(false)
 const load=()=>{setLoading(true);Promise.all([api.inventory.list({limit:50,search:search||undefined}),api.inventory.movements({limit:20})]).then(([p,m])=>{setProducts(p.products);setMovements(m.movements)}).catch(e=>onToast('error',e.message)).finally(()=>setLoading(false))};useEffect(load,[search]);const canMove=user.role==='ADMIN'||user.role==='WAREHOUSE'
 return <div className="content-page"><div className="content-title"><div><p className="eyebrow">WAREHOUSE CONTROL</p><h1>Inventory</h1><p>See stock health and every movement across the operation.</p></div>{canMove&&<Button onClick={()=>setOpen(true)}><PackagePlus size={16}/> Record movement</Button>}</div><div className="inventory-strip"><Card><span>Total units</span><strong>{products.reduce((a,p)=>a+p.current_stock,0).toLocaleString('en-IN')}</strong><small>Across {products.length} visible products</small></Card><Card><span>Low stock</span><strong className="attention">{products.filter(p=>p.current_stock<=p.minimum_stock).length}</strong><small>Need replenishment</small></Card><Card><span>Movements</span><strong>{movements.length}</strong><small>Latest activity</small></Card></div><Card className="table-card"><div className="toolbar"><div className="tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}><SlidersHorizontal size={15}/> Stock levels</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History size={15}/> Movement history</button></div><div className="search-box compact"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter products..."/></div></div>{loading?<TableSkeleton/>:tab==='stock'?<StockTable products={products}/>:<MovementTable movements={movements}/>}</Card><Modal open={open} onClose={()=>setOpen(false)} title="Record inventory movement"><MovementForm products={products} onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}} onToast={onToast}/></Modal></div>
}
function StockTable({products}:{products:Product[]}){if(!products.length)return <Empty title="No inventory" description="Products will appear here once they are created."/>;return <div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Available</th><th>Threshold</th><th>Health</th><th>Location</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="entity"><div className="entity-avatar"><span>{p.name[0]}</span></div><div><b>{p.name}</b><span>{p.category}</span></div></div></td><td className="mono">{p.sku}</td><td><strong className={p.current_stock<=p.minimum_stock?'attention':''}>{p.current_stock}</strong></td><td>{p.minimum_stock}</td><td><Badge tone={p.current_stock<=p.minimum_stock?'warning':'success'}>{p.current_stock<=p.minimum_stock?'LOW':'HEALTHY'}</Badge></td><td>{p.warehouse_location||'—'}</td></tr>)}</tbody></table></div>}
function MovementTable({movements}:{movements:any[]}){if(!movements.length)return <Empty title="No movement history" description="Inventory changes will appear here."/>;return <div className="table-wrap"><table><thead><tr><th>Product</th><th>Direction</th><th>Quantity</th><th>Reason</th><th>Created by</th><th>Time</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td><b>{m.product?.name}</b><span className="table-sub mono">{m.product?.sku}</span></td><td><Badge tone={m.movement_type==='IN'?'success':'danger'}>{m.movement_type==='IN'?'INBOUND':'OUTBOUND'}</Badge></td><td><strong className={m.movement_type==='IN'?'positive':'negative'}>{m.movement_type==='IN'?'+':'-'}{m.quantity}</strong></td><td>{m.reason||'—'}</td><td>{m.creator?.name||'—'}</td><td>{dateTime(m.created_at)}</td></tr>)}</tbody></table></div>}
function MovementForm({products,onClose,onSaved,onToast}:{products:Product[];onClose:()=>void;onSaved:()=>void;onToast:(t:'success'|'error',m:string)=>void}){const [f,setF]=useState({product_id:products[0]?.id||'',quantity:'',movement_type:'IN' as 'IN'|'OUT',reason:''});const [saving,setSaving]=useState(false);const selected=products.find(p=>p.id===f.product_id);const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{await api.inventory.move({product_id:f.product_id,quantity:Number(f.quantity),movement_type:f.movement_type,reason:f.reason||undefined});onToast('success',`Stock ${f.movement_type==='IN'?'added':'removed'} successfully`);onSaved()}catch(e:any){onToast('error',e.message)}finally{setSaving(false)}};return <form className="stack-form" onSubmit={submit}><label className="field"><span>Product</span><select required value={f.product_id} onChange={e=>setF({...f,product_id:e.target.value})}>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku} · {p.current_stock} available</option>)}</select></label><div className="segmented"><button type="button" className={f.movement_type==='IN'?'active in':''} onClick={()=>setF({...f,movement_type:'IN'})}><ArrowDownLeft size={15}/> Stock IN</button><button type="button" className={f.movement_type==='OUT'?'active out':''} onClick={()=>setF({...f,movement_type:'OUT'})}><ArrowUpRight size={15}/> Stock OUT</button></div><label className="field"><span>Quantity</span><input required min="1" type="number" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})} placeholder="10"/>{f.movement_type==='OUT'&&selected&&<small className="field-hint">Available: {selected.current_stock} units</small>}</label><label className="field"><span>Reason</span><input value={f.reason} onChange={e=>setF({...f,reason:e.target.value})} placeholder="Purchase receipt / adjustment / damage..."/></label><div className="modal-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit" loading={saving}>Record movement</Button></div></form>}
function TableSkeleton(){return <div className="table-skeleton">{[1,2,3,4,5].map(i=><div key={i}/>)}</div>}
