import { FormEvent, useEffect, useState } from 'react'
import { ArrowUpRight, Boxes, Edit3, MapPin, Plus, Search, Trash2 } from 'lucide-react'
import { api } from '../lib/api'
import type { Product, User } from '../types'
import { Badge, Button, Card, Empty, Modal } from '../components/ui'
import { money, dateTime } from '../lib/utils'

export function Products({user,onToast}:{user:User;onToast:(t:'success'|'error',m:string)=>void}){
 const [rows,setRows]=useState<Product[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[page,setPage]=useState(1),[total,setTotal]=useState(0),[open,setOpen]=useState(false),[selected,setSelected]=useState<Product|null>(null)
 const load=()=>{setLoading(true);api.products.list({page,limit:10,search:search||undefined}).then(r=>{setRows(r.products);setTotal(r.total)}).catch(e=>onToast('error',e.message)).finally(()=>setLoading(false))};useEffect(load,[page,search]);const canEdit=user.role==='ADMIN'||user.role==='WAREHOUSE';const canDelete=user.role==='ADMIN'
 return <div className="content-page"><div className="content-title"><div><p className="eyebrow">CATALOG + INVENTORY</p><h1>Products</h1><p>Manage your catalogue, pricing and stock thresholds.</p></div>{canEdit&&<Button onClick={()=>{setSelected(null);setOpen(true)}}><Plus size={16}/> Add product</Button>}</div><div className="product-bento">{rows.slice(0,3).map((p,i)=><Card key={p.id} className={`product-spotlight s${i}`}><div className="spotlight-top"><div className="product-avatar large">{p.name.slice(0,1)}</div><Badge tone={p.current_stock<=p.minimum_stock?'warning':'success'}>{p.current_stock<=p.minimum_stock?'LOW STOCK':'HEALTHY'}</Badge></div><div><h3>{p.name}</h3><span>{p.sku} · {p.category}</span></div><div className="spotlight-bottom"><strong>{money(p.unit_price)}</strong><small>{p.current_stock} units available</small></div></Card>)}</div><Card className="table-card"><div className="toolbar"><div className="search-box"><Search size={16}/><input value={search} onChange={e=>{setPage(1);setSearch(e.target.value)}} placeholder="Search products, SKU or category..."/></div><div className="toolbar-meta">{total} products</div></div>{loading?<TableSkeleton/>:rows.length===0?<Empty title="No products found" description="Try a different search or create a product."/>:<><div className="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Unit price</th><th>Stock</th><th>Warehouse</th><th></th></tr></thead><tbody>{rows.map(p=><tr className="clickable" key={p.id} onClick={()=>{setSelected(p);setOpen(true)}}><td><div className="entity"><div className="entity-avatar"><Boxes size={16}/></div><div><b>{p.name}</b><span className="mono">{p.sku}</span></div></div></td><td><Badge tone="neutral">{p.category}</Badge></td><td>{money(p.unit_price)}</td><td><div className="stock-cell"><strong>{p.current_stock}</strong><span>min {p.minimum_stock}</span></div></td><td><span className="location"><MapPin size={13}/>{p.warehouse_location||'Unassigned'}</span></td><td><ArrowUpRight size={16}/></td></tr>)}</tbody></table></div><Pagination page={page} total={total} limit={10} setPage={setPage}/></>}</Card><Modal open={open} onClose={()=>setOpen(false)} title={selected?'Product details':'Add product'} wide>{selected?<ProductDetail product={selected} canEdit={canEdit} canDelete={canDelete} onClose={()=>setOpen(false)} onRefresh={()=>{setOpen(false);load()}} onToast={onToast}/>:<ProductForm onClose={()=>setOpen(false)} onSaved={()=>{setOpen(false);load()}} onToast={onToast}/>}</Modal></div>
}
function ProductForm({initial,onClose,onSaved,onToast}:{initial?:Product;onClose:()=>void;onSaved:()=>void;onToast:(t:'success'|'error',m:string)=>void}){const [f,setF]=useState({name:initial?.name||'',sku:initial?.sku||'',category:initial?.category||'',unit_price:String(initial?.unit_price||''),current_stock:String(initial?.current_stock??0),minimum_stock:String(initial?.minimum_stock??0),warehouse_location:initial?.warehouse_location||''});const [saving,setSaving]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const body={...f,unit_price:Number(f.unit_price),current_stock:Number(f.current_stock),minimum_stock:Number(f.minimum_stock)};if(initial)await api.products.update(initial.id,body);else await api.products.create(body);onToast('success',initial?'Product updated':'Product created');onSaved()}catch(e:any){onToast('error',e.message)}finally{setSaving(false)}};return <form className="form-grid" onSubmit={submit}><Field label="Product name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Safety Helmet Yellow"/></Field><Field label="SKU"><input required disabled={!!initial} value={f.sku} onChange={e=>setF({...f,sku:e.target.value})} placeholder="SKU-001"/></Field><Field label="Category"><input required value={f.category} onChange={e=>setF({...f,category:e.target.value})} placeholder="Safety"/></Field><Field label="Unit price"><input required min="0" step="0.01" type="number" value={f.unit_price} onChange={e=>setF({...f,unit_price:e.target.value})} placeholder="1499"/></Field><Field label="Current stock"><input required min="0" type="number" value={f.current_stock} onChange={e=>setF({...f,current_stock:e.target.value})}/></Field><Field label="Minimum stock"><input required min="0" type="number" value={f.minimum_stock} onChange={e=>setF({...f,minimum_stock:e.target.value})}/></Field><Field label="Warehouse location"><input value={f.warehouse_location} onChange={e=>setF({...f,warehouse_location:e.target.value})} placeholder="WH-A / Rack 03"/></Field><div className="modal-actions"><Button variant="secondary" type="button" onClick={onClose}>Cancel</Button><Button type="submit" loading={saving}>{initial?'Save changes':'Create product'}</Button></div></form>}
function ProductDetail({product,canEdit,canDelete,onClose,onRefresh,onToast}:{product:Product;canEdit:boolean;canDelete:boolean;onClose:()=>void;onRefresh:()=>void;onToast:(t:'success'|'error',m:string)=>void}){const [edit,setEdit]=useState(false);const [fresh,setFresh]=useState(product);useEffect(()=>{api.products.get(product.id).then(setFresh).catch(()=>{})},[product.id]);if(edit)return <ProductForm initial={fresh} onClose={()=>setEdit(false)} onSaved={onRefresh} onToast={onToast}/>;return <div><div className="profile-hero"><div className="profile-avatar product"><Boxes size={25}/></div><div><h3>{fresh.name}</h3><p className="mono">{fresh.sku} · {fresh.category}</p></div><div className="profile-status"><Badge tone={fresh.current_stock<=fresh.minimum_stock?'warning':'success'}>{fresh.current_stock<=fresh.minimum_stock?'LOW STOCK':'HEALTHY'}</Badge></div></div><div className="detail-grid"><div className="detail-block"><span>Unit price</span><b>{money(fresh.unit_price)}</b></div><div className="detail-block"><span>Current stock</span><b>{fresh.current_stock} units</b></div><div className="detail-block"><span>Minimum threshold</span><b>{fresh.minimum_stock} units</b></div><div className="detail-block"><span>Warehouse</span><b>{fresh.warehouse_location||'Unassigned'}</b></div></div><div className="detail-section"><div className="section-head"><div><p className="eyebrow">MOVEMENT HISTORY</p><h3>Recent stock activity</h3></div></div>{fresh.stock_movements?.length?<div className="activity-list">{fresh.stock_movements.slice(0,8).map(m=><div className="activity-row" key={m.id}><div className={`movement-dot ${m.movement_type==='IN'?'in':'out'}`}>{m.movement_type}</div><div><b>{m.reason||'Inventory movement'}</b><span>{dateTime(m.created_at)}</span></div><strong className={m.movement_type==='IN'?'positive':'negative'}>{m.movement_type==='IN'?'+':'-'}{m.quantity}</strong></div>)}</div>:<Empty title="No movements" description="Inventory activity will appear here."/>}</div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Close</Button>{canDelete&&<Button variant="danger" onClick={async()=>{if(!confirm('Delete this product?'))return;try{await api.products.remove(fresh.id);onToast('success','Product deleted');onRefresh()}catch(e:any){onToast('error',e.message)}}}><Trash2 size={15}/> Delete</Button>}{canEdit&&<Button onClick={()=>setEdit(true)}><Edit3 size={15}/> Edit product</Button>}</div></div>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
function Pagination({page,total,limit,setPage}:{page:number;total:number;limit:number;setPage:(n:number)=>void}){const pages=Math.max(1,Math.ceil(total/limit));return <div className="pagination"><span>Page {page} of {pages}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div>}
function TableSkeleton(){return <div className="table-skeleton">{[1,2,3,4,5].map(i=><div key={i}/>)}</div>}
