import { useEffect,useMemo,useState } from 'react';
import { ArrowRight, Check, ChevronDown, ClipboardList, FilePlus2, Plus, Search, Trash2, X } from 'lucide-react';
import { apiClient } from '../lib/api';
import type { Challan, Customer, Product } from '../types';
import Modal from '../components/Modal';
import { dateTime, money } from '../lib/utils';

export default function Challans(){
 const [rows,setRows]=useState<Challan[]>([]);const [customers,setCustomers]=useState<Customer[]>([]);const [products,setProducts]=useState<Product[]>([]);const [status,setStatus]=useState('');const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [selected,setSelected]=useState<Challan|null>(null);const [customer,setCustomer]=useState('');const [items,setItems]=useState<{product_id:string;quantity:number}[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const load=()=>apiClient.challans(`?page=1&limit=50${status?`&status=${status}`:''}`).then(r=>setRows(r.data||r)).catch(e=>setError(e.message));useEffect(()=>{load();apiClient.customers('?page=1&limit=100').then(r=>setCustomers(r.data||r));apiClient.products('?page=1&limit=100').then(r=>setProducts(r.data||r))},[]);useEffect(()=>{load()},[status]);
 const visible=rows.filter(r=>!q||r.challan_number.toLowerCase().includes(q.toLowerCase())||(r.customer?.name||'').toLowerCase().includes(q.toLowerCase()));
 const total=useMemo(()=>items.reduce((s,i)=>s+i.quantity,0),[items]);
 function addItem(){setItems(x=>[...x,{product_id:products[0]?.id||'',quantity:1}])};function setItem(i:number,k:string,v:any){setItems(x=>x.map((it,n)=>n===i?{...it,[k]:v}:it))};function removeItem(i:number){setItems(x=>x.filter((_,n)=>n!==i))};
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const r=await apiClient.createChallan({customer_id:customer,items:items.map(i=>({...i,quantity:Number(i.quantity)}))});setOpen(false);setCustomer('');setItems([]);load();setSelected(r)}catch(e){setError(e instanceof Error?e.message:'Could not create challan')}finally{setSaving(false)}}
 async function action(id:string,type:'confirm'|'cancel'){try{if(!confirm(`Are you sure you want to ${type} this challan?`))return;type==='confirm'?await apiClient.confirmChallan(id):await apiClient.cancelChallan(id);load();if(selected?.id===id)setSelected(await apiClient.challan(id))}catch(e){setError(e instanceof Error?e.message:'Action failed')}}
 return <div><div className="page-header"><div className="page-heading"><div className="page-icon"><ClipboardList/></div><div><span className="section-kicker">SALES</span><h2>Sales challans</h2><p>Draft, confirm and track every outgoing order document.</p></div></div><button className="primary-btn" onClick={()=>{setOpen(true);if(!items.length)addItem()}}><FilePlus2 size={17}/> Create challan</button></div><div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search challan or customer..."/></div><div className="status-tabs"><button className={!status?'active':''} onClick={()=>setStatus('')}>All</button>{['DRAFT','CONFIRMED','CANCELLED'].map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s}</button>)}</div></div>{error&&<div className="inline-error">{error}</div>}
 <div className="challan-layout"><div className="table-card"><div className="data-table"><div className="table-header"><span>Document</span><span>Customer</span><span>Items</span><span>Status</span><span>Created</span><span/></div>{visible.map(c=><button className="table-row challan-row" key={c.id} onClick={()=>setSelected(c)}><div className="person-cell"><div className="doc-icon"><ClipboardList size={15}/></div><div><b>{c.challan_number}</b><small>{c.total_quantity} total units</small></div></div><span>{c.customer?.business_name||c.customer?.name||'—'}</span><span className="pill">{c._count?.items||c.items?.length||0} items</span><Status status={c.status}/><span>{dateTime(c.created_at)}</span><ArrowRight size={16}/></button>)}</div></div>
 {selected&&<aside className="detail-drawer"><div className="drawer-head"><div><span className="panel-eyebrow">DOCUMENT</span><h3>{selected.challan_number}</h3></div><button className="icon-btn" onClick={()=>setSelected(null)}><X size={18}/></button></div><Status status={selected.status}/><div className="drawer-customer"><span>Customer</span><b>{selected.customer?.business_name||selected.customer?.name}</b><small>{selected.customer?.name}</small></div><div className="drawer-items"><span className="panel-eyebrow">LINE ITEMS</span>{selected.items?.map(i=><div className="drawer-item" key={i.id}><div><b>{i.product_name_snapshot}</b><small>{i.sku_snapshot}</small></div><span>{i.quantity}</span></div>)||<div className="drawer-empty">Open a document to see its line items.</div>}</div><div className="drawer-actions">{selected.status==='DRAFT'&&<><button className="soft-btn danger" onClick={()=>action(selected.id,'cancel')}><X size={15}/> Cancel</button><button className="primary-btn" onClick={()=>action(selected.id,'confirm')}><Check size={15}/> Confirm & deduct stock</button></>}</div></aside>}
 </div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Create sales challan" wide><form onSubmit={create}><div className="challan-form-top"><label>Customer<select required value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Choose customer...</option>{customers.map(c=><option value={c.id} key={c.id}>{c.business_name||c.name}</option>)}</select></label><div className="draft-note"><span>DRAFT</span><small>Stock is only deducted after confirmation.</small></div></div><div className="line-items-head"><span>Products</span><button type="button" className="soft-btn" onClick={addItem}><Plus size={15}/> Add line</button></div><div className="line-items">{items.map((it,i)=><div className="line-item" key={i}><select required value={it.product_id} onChange={e=>setItem(i,'product_id',e.target.value)}><option value="">Choose product...</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.sku} · {p.current_stock} available</option>)}</select><input required min="1" type="number" value={it.quantity} onChange={e=>setItem(i,'quantity',Number(e.target.value))}/><button type="button" onClick={()=>removeItem(i)}><Trash2 size={16}/></button></div>)}</div><div className="challan-total"><span>Total quantity</span><strong>{total}</strong></div>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="soft-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Creating...':<>Save draft <ArrowRight size={16}/></>}</button></div></form></Modal>
 </div>
}
function Status({status}:{status:string}){return <span className={`status ${status.toLowerCase()}`}><i/>{status}</span>}
