import { useEffect,useState } from 'react';
import { Building2, Edit3, Mail, Phone, Plus, Search, Trash2, UserRound, UsersRound } from 'lucide-react';
import { apiClient } from '../lib/api';
import type { Customer } from '../types';
import Modal from '../components/Modal';
import { dateOnly } from '../lib/utils';

const empty={name:'',mobile:'',email:'',business_name:'',gst_number:'',customer_type:'RETAIL',address:'',status:'ACTIVE'};
export default function Customers(){
 const [rows,setRows]=useState<Customer[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState(''); const [open,setOpen]=useState(false); const [selected,setSelected]=useState<Customer|null>(null); const [form,setForm]=useState<any>(empty); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const load=()=>{setLoading(true);apiClient.customers(`?page=1&limit=50${q?`&search=${encodeURIComponent(q)}`:''}`).then(r=>setRows(r.data||r)).catch(e=>setError(e.message)).finally(()=>setLoading(false));}; useEffect(()=>{const t=setTimeout(load,220);return()=>clearTimeout(t)},[q]);
 const edit=(c:Customer)=>{setSelected(c);setForm({...empty,...c});setOpen(true)}; const add=()=>{setSelected(null);setForm({...empty});setOpen(true)};
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{selected?await apiClient.updateCustomer(selected.id,form):await apiClient.createCustomer(form);setOpen(false);load();}catch(e){setError(e instanceof Error?e.message:'Could not save customer')}finally{setSaving(false)}}
 async function remove(c:Customer){if(!confirm(`Delete ${c.name}?`))return;try{await apiClient.deleteCustomer(c.id);load()}catch(e){setError(e instanceof Error?e.message:'Could not delete customer')}}
 return <div><PageHeader icon={<UsersRound/>} title="Customers" subtitle="Relationships, follow-ups and the people behind every order." action={<button className="primary-btn" onClick={add}><Plus size={17}/> Add customer</button>}/>
 <div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, business or email..."/></div><span className="result-count">{rows.length} customers</span></div>
 {error&&<div className="inline-error">{error}</div>}
 <div className="table-card"><div className="data-table customer-table"><div className="table-header"><span>Customer</span><span>Business</span><span>Type</span><span>Status</span><span>Contact</span><span/></div>{loading?<RowsSkeleton/>:rows.map(c=><div className="table-row" key={c.id}><div className="person-cell"><div className="avatar soft">{c.name.slice(0,1).toUpperCase()}</div><div><b>{c.name}</b><small>{c.email||'No email'}</small></div></div><div className="business-cell"><Building2 size={15}/><span>{c.business_name||'—'}</span></div><span className="pill">{c.customer_type}</span><span className={`status ${c.status.toLowerCase()}`}><i/>{c.status}</span><div className="contact-cell"><span><Phone size={13}/>{c.mobile}</span></div><div className="row-actions"><button onClick={()=>edit(c)} title="Edit"><Edit3 size={15}/></button><button onClick={()=>remove(c)} title="Delete"><Trash2 size={15}/></button></div></div>)}</div></div>
 <Modal open={open} onClose={()=>setOpen(false)} title={selected?'Edit customer':'Add customer'} wide><form className="form-grid" onSubmit={save}>{['name','mobile','email','business_name','gst_number'].map((k)=><label key={k}>{k.replace('_',' ')}<input required={k==='name'||k==='mobile'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Customer type<select value={form.customer_type} onChange={e=>setForm({...form,customer_type:e.target.value})}><option>RETAIL</option><option>WHOLESALE</option><option>DISTRIBUTOR</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><label className="span-2">Address<textarea rows={3} value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label>{error&&<div className="form-error span-2">{error}</div>}<div className="form-actions span-2"><button type="button" className="soft-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving...':selected?'Save changes':'Create customer'}</button></div></form></Modal>
 </div>
}
function PageHeader({icon,title,subtitle,action}:{icon:React.ReactNode;title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-header"><div className="page-heading"><div className="page-icon">{icon}</div><div><span className="section-kicker">WORKSPACE</span><h2>{title}</h2><p>{subtitle}</p></div></div>{action}</div>}
function RowsSkeleton(){return <>{[1,2,3,4,5].map(i=><div className="table-row" key={i}><div className="skeleton-line w180"/><div className="skeleton-line w120"/><div className="skeleton-line w80"/><div className="skeleton-line w80"/><div className="skeleton-line w110"/><div/></div>)}</>}
