import { useEffect,useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Boxes, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { apiClient } from '../lib/api';
import type { Movement, Product } from '../types';
import Modal from '../components/Modal';
import { dateTime } from '../lib/utils';

export default function Inventory(){
 const [products,setProducts]=useState<Product[]>([]);const [moves,setMoves]=useState<Movement[]>([]);const [q,setQ]=useState('');const [low,setLow]=useState(false);const [tab,setTab]=useState<'stock'|'movements'>('stock');const [open,setOpen]=useState(false);const [form,setForm]=useState({product_id:'',quantity:1,movement_type:'IN',reason:''});const [error,setError]=useState('');
 const load=()=>{apiClient.inventory(`?page=1&limit=100${q?`&search=${encodeURIComponent(q)}`:''}${low?'&low_stock=true':''}`).then(r=>setProducts(r.data||r)).catch(e=>setError(e.message));apiClient.movements('?page=1&limit=30').then(r=>setMoves(r.data||r)).catch(()=>{})};useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[q,low]);
 async function save(e:React.FormEvent){e.preventDefault();try{await apiClient.createMovement({...form,quantity:Number(form.quantity)});setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:'Could not create movement')}}
 return <div><div className="page-header"><div className="page-heading"><div className="page-icon"><Boxes/></div><div><span className="section-kicker">WAREHOUSE</span><h2>Inventory</h2><p>A live view of stock health and movement history.</p></div></div><button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> Stock movement</button></div><div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search inventory..."/></div><button className={low?'filter-btn active':'filter-btn'} onClick={()=>setLow(v=>!v)}><SlidersHorizontal size={15}/> Low stock only</button></div><div className="segmented"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}>Stock levels</button><button className={tab==='movements'?'active':''} onClick={()=>setTab('movements')}>Movement log</button></div>{error&&<div className="inline-error">{error}</div>}
 {tab==='stock'?<div className="stock-grid">{products.map(p=><div className="stock-card" key={p.id}><div className="stock-card-head"><div className="product-symbol small">{p.name.slice(0,1)}</div><span className={p.current_stock<=p.minimum_stock?'stock-badge low':'stock-badge healthy'}>{p.current_stock<=p.minimum_stock?'Low':'Healthy'}</span></div><h3>{p.name}</h3><span>{p.sku} · {p.warehouse_location||'Main warehouse'}</span><div className="stock-big"><b>{p.current_stock}</b><small>units</small></div><div className="progress"><i className={p.current_stock<=p.minimum_stock?'low':''} style={{width:`${Math.min(100,Math.max(5,(p.current_stock/Math.max(1,p.minimum_stock*4))*100))}%`}}/></div><div className="stock-card-foot"><span>Minimum {p.minimum_stock}</span><span>{p.current_stock<=p.minimum_stock?'Restock needed':'In range'}</span></div></div>)}</div>:<div className="table-card"><div className="data-table"><div className="table-header"><span>Product</span><span>Type</span><span>Quantity</span><span>Reason</span><span>Created</span></div>{moves.map(m=><div className="table-row" key={m.id}><div className="person-cell"><div className={m.movement_type==='IN'?'move-icon in':'move-icon out'}>{m.movement_type==='IN'?<ArrowDownLeft size={15}/>:<ArrowUpRight size={15}/>}</div><div><b>{m.product?.name}</b><small>{m.product?.sku}</small></div></div><span className={m.movement_type==='IN'?'positive':'negative'}>{m.movement_type==='IN'?'+':'−'}{m.quantity}</span><span className="pill">{m.movement_type}</span><span className="reason-cell">{m.reason}</span><span>{dateTime(m.created_at)}</span></div>)}</div></div>}
 <Modal open={open} onClose={()=>setOpen(false)} title="Record stock movement"><form className="form-grid" onSubmit={save}><label className="span-2">Product<select required value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">Choose product...</option>{products.map(p=><option value={p.id} key={p.id}>{p.name} · {p.sku} ({p.current_stock} in stock)</option>)}</select></label><label>Movement<select value={form.movement_type} onChange={e=>setForm({...form,movement_type:e.target.value})}><option value="IN">IN — received</option><option value="OUT">OUT — issued</option></select></label><label>Quantity<input required min="1" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label className="span-2">Reason<input required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="e.g. Purchase receipt, adjustment..."/></label><div className="form-actions span-2"><button type="button" className="soft-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn">Record movement</button></div></form></Modal>
 </div>
}
