import { useEffect,useState } from 'react';
import { Edit3, Package, Plus, Search, Trash2 } from 'lucide-react';
import { apiClient } from '../lib/api';
import type { Product } from '../types';
import Modal from '../components/Modal';
import { money } from '../lib/utils';

const empty={name:'',sku:'',category:'',unit_price:0,current_stock:0,minimum_stock:5,warehouse_location:''};
export default function Products(){
 const [rows,setRows]=useState<Product[]>([]);const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [selected,setSelected]=useState<Product|null>(null);const [form,setForm]=useState<any>(empty);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 const load=()=>apiClient.products(`?page=1&limit=50${q?`&search=${encodeURIComponent(q)}`:''}`).then(r=>setRows(r.data||r)).catch(e=>setError(e.message));useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[q]);
 function add(){setSelected(null);setForm({...empty});setOpen(true)}function edit(p:Product){setSelected(p);setForm({...p});setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const body={...form,unit_price:Number(form.unit_price),current_stock:Number(form.current_stock),minimum_stock:Number(form.minimum_stock)};selected?await apiClient.updateProduct(selected.id,body):await apiClient.createProduct(body);setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:'Could not save product')}finally{setSaving(false)}}
 async function remove(p:Product){if(!confirm(`Delete ${p.name}?`))return;try{await apiClient.deleteProduct(p.id);load()}catch(e){setError(e instanceof Error?e.message:'Could not delete product')}}
 return <div><div className="page-header"><div className="page-heading"><div className="page-icon"><Package/></div><div><span className="section-kicker">CATALOG</span><h2>Products</h2><p>Your product master, pricing and stock thresholds.</p></div></div><button className="primary-btn" onClick={add}><Plus size={17}/> Add product</button></div><div className="toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product or SKU..."/></div><div className="toolbar-meta"><span>{rows.length} products</span><span className="legend"><i className="dot lime"/>Healthy <i className="dot amber"/>Low stock</span></div></div>{error&&<div className="inline-error">{error}</div>}
 <div className="product-grid">{rows.map((p,i)=><div className="product-card" key={p.id} style={{animationDelay:`${i*30}ms`}}><div className="product-card-top"><div className="product-symbol">{p.name.slice(0,1).toUpperCase()}</div><div className="product-actions"><button onClick={()=>edit(p)}><Edit3 size={15}/></button><button onClick={()=>remove(p)}><Trash2 size={15}/></button></div></div><div className="product-name"><h3>{p.name}</h3><span>{p.sku} · {p.category}</span></div><div className="product-price">{money(p.unit_price)} <small>/ unit</small></div><div className="stock-progress"><div><span>Stock</span><b>{p.current_stock}</b></div><div className="progress"><i className={p.current_stock<=p.minimum_stock?'low':''} style={{width:`${Math.min(100,Math.max(4,(p.current_stock/Math.max(1,p.minimum_stock*4))*100))}%`}}/></div><div className="product-foot"><span>{p.current_stock<=p.minimum_stock?'Reorder soon':'Healthy stock'}</span><small>Min {p.minimum_stock}</small></div></div></div>)}{!rows.length&&<div className="empty-card"><Package size={28}/><b>No products found</b><span>Try another search or add your first product.</span></div>}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title={selected?'Edit product':'Add product'}><form className="form-grid" onSubmit={save}><label className="span-2">Product name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>SKU<input required disabled={!!selected} value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/></label><label>Category<input required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Unit price<input required type="number" min="0" step="0.01" value={form.unit_price} onChange={e=>setForm({...form,unit_price:e.target.value})}/></label><label>Current stock<input type="number" min="0" value={form.current_stock} onChange={e=>setForm({...form,current_stock:e.target.value})}/></label><label>Minimum stock<input type="number" min="0" value={form.minimum_stock} onChange={e=>setForm({...form,minimum_stock:e.target.value})}/></label><label>Warehouse location<input value={form.warehouse_location||''} onChange={e=>setForm({...form,warehouse_location:e.target.value})}/></label>{error&&<div className="form-error span-2">{error}</div>}<div className="form-actions span-2"><button type="button" className="soft-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving...':selected?'Save changes':'Create product'}</button></div></form></Modal>
 </div>
}
